services:
  db:
    image: ${SQL_Image}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_Password}
    ports:
      - "${SQL_Port_Host}:${SQL_Port}"
    volumes:
      - db-data:/var/lib/mysql
      - ./Docker/scriptSql:/docker-entrypoint-initdb.d
      - ./script:/script
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${SQL_Password}"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: ${PhpMyAdmin_Image}
    restart: always
    ports:
      - "${PhpMyAdmin_Port_Host}:${PhpMyAdmin_Port}"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${SQL_Password}
  
  maven:
    build:
      context: .
      dockerfile: Docker/Dockerfile.maven
    volumes:
      - .:/app
    command: >
          sh -c "mvn install && mvn validate && exit 0 || exit 1"
    depends_on:
      db :
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mvn", "validate"]
      interval: 30s
      timeout: 10s
      retries: 3 

  tomcat:
    volumes:
      - ./target/_00_ASBank2023-0.0.1-SNAPSHOT:/usr/local/tomcat/webapps/_00_ASBank2023
    working_dir: /app
    build:
      context: .
      dockerfile: Docker/Dockerfile.tomcat
    ports:
      - "8080:8080"
    depends_on:
      maven :
        condition: service_healthy

volumes:
  db-data: