services:
  db:
    image: ${SQL_Image}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_Password}
    ports:
      - "${SQL_Port_Host}:${SQL_Port}"
    volumes:
      - db-data:/var/lib/mysql
      - ./Docker/scriptSql:/docker-entrypoint-initdb.d
      - ./script:/script
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${SQL_Password}"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: ${PhpMyAdmin_Image}
    restart: always
    ports:
      - "${PhpMyAdmin_Port_Host}:${PhpMyAdmin_Port}"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${SQL_Password}

  tomcat:
    volumes:
      - ./target:/usr/local/tomcat/webapps
    working_dir: /app
    build:
      context: .
      dockerfile: Docker/Dockerfile.tomcat
    ports:
      - "8080:8080"
    depends_on:
      db :
        condition: service_healthy

volumes:
  db-data: