services:
  db:
    container_name: asbank_db
    image: ${SQL_Image}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_Password}
    ports:
      - "${SQL_Port_Host}:${SQL_Port}"
    volumes:
      - db-data:/var/lib/mysql
      - ./Docker/scriptSql:/docker-entrypoint-initdb.d
      - ./script:/script
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${SQL_Password}"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  maven-builder:
    container_name: asbank_maven
    build:
        context: .
        dockerfile: Docker/Dockerfile.maven
    working_dir: /app
    volumes:
      - ./:/app
      - tomcat_data:/app/target/_00_ASBank2023-0.0.1-SNAPSHOT
      - ./target:/app/target
    depends_on:
      - db

  tomcat:
    container_name: asbank_tomcat
    volumes:
      - tomcat_data:/usr/local/tomcat/webapps/_00_ASBank2023
    build:
      context: .
      dockerfile: Docker/Dockerfile.tomcat
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db-data:
  tomcat_data: