package com.iut.banque.selenium;

import java.time.Duration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
//Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

public class TestsSelenium {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    private String appPath = "http://localhost:8081/_00_ASBank2023/";


    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "src\\main\\resources\\chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void testLogo() {
        try{
            driver.get(appPath);
        }
        catch (WebDriverException e) {
            System.out.println("The app couldn't be accessed, Selenium tests aborted");
            return;
        }
        driver.manage().window().setSize(new Dimension(550, 694));
        try{
            WebElement logo = driver.findElement(By.id("logo"));
            Assert.assertNotNull(logo);
        }
        catch (NoSuchElementException e) {
            Assert.fail("The logo couldn't be found");
        }
        driver.close();
    }

    @Test
    public void testLogin() {
        try{
            driver.get(appPath);
        }
        catch (WebDriverException e) {
            System.out.println("The app couldn't be accessed, Selenium tests aborted");
            return;
        }
        driver.manage().window().setSize(new Dimension(550, 694));

        try{
            WebElement loginButton = driver.findElement(By.id("login-button"));
            Assert.assertNotNull(loginButton);

            loginButton.click();
        }
        catch (NoSuchElementException e) {
            Assert.fail("The login button couldn't be found");
        }

        try{
            WebElement userCdeInput = driver.findElement(By.id("controller_Connect_login_action_userCde"));
            WebElement userPwdInput = driver.findElement(By.id("controller_Connect_login_action_userPwd"));
            WebElement loginSubmitButton = driver.findElement(By.id("controller_Connect_login_action_submit"));


            userCdeInput.sendKeys("client1");
            userPwdInput.sendKeys("clientpass1");
            loginSubmitButton.click();
        }
        catch (NoSuchElementException e){
            Assert.fail("The login inputs couldn't be found");
        }

        driver.close();
    }

}
