package com.iut.banque.selenium;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
//Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

public class TestsSelenium {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;


    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "src\\main\\resources\\chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void testLogo() {
        driver.get("http://localhost:8081/_00_ASBank2023/");
        driver.manage().window().setSize(new Dimension(550, 694));
        try{
            WebElement logo = driver.findElement(By.id("logo"));
            Assert.assertNotNull(logo);
        }
        catch (NoSuchElementException e) {
            Assert.fail("The logo couldn't be found");
        }
        driver.close();
    }

}
