# This workflow will deploy the docker application

name: Docker deployment

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Install DBSM
      run: |
        sudo apt update
        sudo apt install mysql-server-8.0

    - name: Create MySQL Socket Directory
      run: |
        sudo mkdir -p /var/run/mysqld
        sudo chown mysql:mysql /var/run/mysqld

    - name: Set root password and database tables
      run: |
        sudo systemctl stop mysql

        sudo mysqld_safe --skip-grant-tables & sleep 5
        sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${{ secrets.DATABASE_ROOT_PASSWORD }}';"
        sudo mysql -e "FLUSH PRIVILEGES;"
        sudo killall mysqld
        sleep 5


    - name: Start mysql server
      run: |
        sudo systemctl start mysql
        sudo systemctl is-active --quiet mysql || exit 1

    - name: Verify MySQL
      run: |
        sudo mysql -u root -p${{ secrets.DATABASE_ROOT_PASSWORD }} -e "SELECT VERSION();"

    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      working-directory: _00_ASBank2023
      run: mvn -B package -DskipTests